"use strict";
var cookiconsIconData = [{
	name: "更多",
			    id: "logo",
				url: "#"
			}, {
				name: "未来UI",
				id: "未来UI",
				url: "https://www.coolapk.com/apk/232387"
			}, {
				name: "终端",
				id: "终端",
				url: "https://www.coolapk.com/apk/232382"
			}, {
				name: "未来主义",
				id: "未来主义",
				url: "https://www.coolapk.com/apk/232367"
			}, {
				name: "科幻",
				id: "科幻",
				url: "https://www.coolapk.com/apk/232375"
			}, {
				name: "科技",
				id: "科技",
				url: "https://www.coolapk.com/apk/232378"
			}, {
				name: "科技感",
				id: "科技感",
				url: "https://www.coolapk.com/apk/232361"
			}, {
				name: "黑客",
				id: "黑客",
				url: "https://www.coolapk.com/apk/232371"
			}, {
				name: "极客",
				id: "极客",
				url: "https://www.coolapk.com/apk/232309"
			}, {
				name: "未来",
				id: "未来",
				url: "https://www.coolapk.com/apk/249917"
			}, {
				name: "ARC",
				id: "ARC",
				url: "https://www.coolapk.com/apk/237108"
			}, {
				name: "Agent",
				id: "Agent",
				url: "https://www.coolapk.com/apk/237107"
			}, {
				name: "Scitific",
				id: "Scitific",
				url: "https://www.coolapk.com/apk/237109"
			}, {
				name: "Dashboard",
				id: "Dashboard",
				url: "https://www.coolapk.com/apk/249916"
			}, {
				name: "Trek",
				id: "Trek",
				url: "https://www.coolapk.com/apk/249918"
}];
